# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\STM_Alapproject\urabrospctester/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1602, 907)
        Form.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.MainMessages = QtWidgets.QTextEdit(Form)
        self.MainMessages.setGeometry(QtCore.QRect(1080, 80, 500, 350))
        self.MainMessages.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.MainMessages.setReadOnly(False)
        self.MainMessages.setObjectName("MainMessages")
        self.DebugMessages = QtWidgets.QTextEdit(Form)
        self.DebugMessages.setGeometry(QtCore.QRect(1080, 510, 500, 350))
        self.DebugMessages.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.DebugMessages.setObjectName("DebugMessages")
        self.PbClearMaster = QtWidgets.QPushButton(Form)
        self.PbClearMaster.setGeometry(QtCore.QRect(1080, 440, 291, 23))
        self.PbClearMaster.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbClearMaster.setObjectName("PbClearMaster")
        self.PbClearDebug = QtWidgets.QPushButton(Form)
        self.PbClearDebug.setGeometry(QtCore.QRect(1080, 870, 501, 23))
        self.PbClearDebug.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbClearDebug.setObjectName("PbClearDebug")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(1050, 0, 20, 911))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(1580, 20, 20, 911))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(1020, 20, 21, 701))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(10, 20, 21, 701))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(20, 10, 1011, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(20, 710, 1011, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.Pages = QtWidgets.QStackedWidget(Form)
        self.Pages.setGeometry(QtCore.QRect(30, 30, 991, 681))
        self.Pages.setObjectName("Pages")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 531, 158))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.SbIdAdd = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.SbIdAdd.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.SbIdAdd.setMinimum(1)
        self.SbIdAdd.setMaximum(254)
        self.SbIdAdd.setObjectName("SbIdAdd")
        self.gridLayout.addWidget(self.SbIdAdd, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.PbSendTest = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.PbSendTest.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbSendTest.setObjectName("PbSendTest")
        self.gridLayout.addWidget(self.PbSendTest, 4, 0, 1, 1)
        self.SbIdRemove = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.SbIdRemove.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.SbIdRemove.setMinimum(1)
        self.SbIdRemove.setMaximum(254)
        self.SbIdRemove.setObjectName("SbIdRemove")
        self.gridLayout.addWidget(self.SbIdRemove, 2, 1, 1, 1)
        self.PbAddCommand = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.PbAddCommand.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbAddCommand.setObjectName("PbAddCommand")
        self.gridLayout.addWidget(self.PbAddCommand, 1, 0, 1, 1)
        self.LeDataTest = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LeDataTest.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.LeDataTest.setObjectName("LeDataTest")
        self.gridLayout.addWidget(self.LeDataTest, 4, 2, 1, 1)
        self.PbDeleteCommand = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.PbDeleteCommand.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbDeleteCommand.setObjectName("PbDeleteCommand")
        self.gridLayout.addWidget(self.PbDeleteCommand, 2, 0, 1, 1)
        self.PbSendDataToTask = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.PbSendDataToTask.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbSendDataToTask.setObjectName("PbSendDataToTask")
        self.gridLayout.addWidget(self.PbSendDataToTask, 3, 0, 1, 1)
        self.LeDataToTask = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LeDataToTask.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.LeDataToTask.setObjectName("LeDataToTask")
        self.gridLayout.addWidget(self.LeDataToTask, 3, 2, 1, 1)
        self.SbIdSendData = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.SbIdSendData.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.SbIdSendData.setMinimum(1)
        self.SbIdSendData.setMaximum(254)
        self.SbIdSendData.setObjectName("SbIdSendData")
        self.gridLayout.addWidget(self.SbIdSendData, 3, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 219, 531, 87))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.CbMotorMode = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.CbMotorMode.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.CbMotorMode.setObjectName("CbMotorMode")
        self.CbMotorMode.addItem("")
        self.CbMotorMode.addItem("")
        self.CbMotorMode.addItem("")
        self.CbMotorMode.addItem("")
        self.gridLayout_3.addWidget(self.CbMotorMode, 1, 0, 1, 1)
        self.CbMotorDirection = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.CbMotorDirection.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.CbMotorDirection.setObjectName("CbMotorDirection")
        self.CbMotorDirection.addItem("")
        self.CbMotorDirection.addItem("")
        self.gridLayout_3.addWidget(self.CbMotorDirection, 1, 1, 1, 1)
        self.LeMotorSteps = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.LeMotorSteps.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.LeMotorSteps.setObjectName("LeMotorSteps")
        self.gridLayout_3.addWidget(self.LeMotorSteps, 1, 2, 1, 1)
        self.LeMotorTimeout = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.LeMotorTimeout.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.LeMotorTimeout.setObjectName("LeMotorTimeout")
        self.gridLayout_3.addWidget(self.LeMotorTimeout, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_12.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_11.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 2, 1, 1)
        self.PbSendMotorCommand = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.PbSendMotorCommand.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbSendMotorCommand.setObjectName("PbSendMotorCommand")
        self.gridLayout_3.addWidget(self.PbSendMotorCommand, 2, 0, 1, 4)
        self.Pages.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Pages.addWidget(self.page_2)
        self.PbGetStatus = QtWidgets.QPushButton(Form)
        self.PbGetStatus.setGeometry(QtCore.QRect(930, 740, 121, 23))
        self.PbGetStatus.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbGetStatus.setObjectName("PbGetStatus")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(1080, 50, 511, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CbComMaster = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.CbComMaster.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.CbComMaster.setObjectName("CbComMaster")
        self.horizontalLayout_2.addWidget(self.CbComMaster)
        self.CbBaudMaster = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.CbBaudMaster.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.CbBaudMaster.setObjectName("CbBaudMaster")
        self.CbBaudMaster.addItem("")
        self.CbBaudMaster.addItem("")
        self.horizontalLayout_2.addWidget(self.CbBaudMaster)
        self.PbConnectMaster = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.PbConnectMaster.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbConnectMaster.setObjectName("PbConnectMaster")
        self.horizontalLayout_2.addWidget(self.PbConnectMaster)
        self.PbDisconnectMaster = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.PbDisconnectMaster.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbDisconnectMaster.setObjectName("PbDisconnectMaster")
        self.horizontalLayout_2.addWidget(self.PbDisconnectMaster)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.PbRefreshPorts = QtWidgets.QPushButton(Form)
        self.PbRefreshPorts.setGeometry(QtCore.QRect(1080, 20, 171, 23))
        self.PbRefreshPorts.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbRefreshPorts.setObjectName("PbRefreshPorts")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(1060, 470, 531, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(1500, 490, 92, 20))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.CbPrintIncomingHex = QtWidgets.QCheckBox(Form)
        self.CbPrintIncomingHex.setGeometry(QtCore.QRect(1410, 440, 161, 20))
        self.CbPrintIncomingHex.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.CbPrintIncomingHex.setObjectName("CbPrintIncomingHex")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(650, 730, 261, 176))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TaskId_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskId_5.setObjectName("TaskId_5")
        self.gridLayout_2.addWidget(self.TaskId_5, 5, 0, 1, 1)
        self.TaskId_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskId_3.setObjectName("TaskId_3")
        self.gridLayout_2.addWidget(self.TaskId_3, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.TaskId_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskId_4.setObjectName("TaskId_4")
        self.gridLayout_2.addWidget(self.TaskId_4, 4, 0, 1, 1)
        self.TaskId_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskId_7.setObjectName("TaskId_7")
        self.gridLayout_2.addWidget(self.TaskId_7, 7, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.TaskId_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskId_6.setObjectName("TaskId_6")
        self.gridLayout_2.addWidget(self.TaskId_6, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.TaskId_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskId_2.setObjectName("TaskId_2")
        self.gridLayout_2.addWidget(self.TaskId_2, 2, 0, 1, 1)
        self.TaskId_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskId_1.setObjectName("TaskId_1")
        self.gridLayout_2.addWidget(self.TaskId_1, 1, 0, 1, 1)
        self.TaskId_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskId_8.setObjectName("TaskId_8")
        self.gridLayout_2.addWidget(self.TaskId_8, 8, 0, 1, 1)
        self.TaskMainStatus_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMainStatus_1.setObjectName("TaskMainStatus_1")
        self.gridLayout_2.addWidget(self.TaskMainStatus_1, 1, 1, 1, 1)
        self.TaskMainStatus_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMainStatus_2.setObjectName("TaskMainStatus_2")
        self.gridLayout_2.addWidget(self.TaskMainStatus_2, 2, 1, 1, 1)
        self.TaskMainStatus_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMainStatus_3.setObjectName("TaskMainStatus_3")
        self.gridLayout_2.addWidget(self.TaskMainStatus_3, 3, 1, 1, 1)
        self.TaskMainStatus_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMainStatus_4.setObjectName("TaskMainStatus_4")
        self.gridLayout_2.addWidget(self.TaskMainStatus_4, 4, 1, 1, 1)
        self.TaskMainStatus_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMainStatus_5.setObjectName("TaskMainStatus_5")
        self.gridLayout_2.addWidget(self.TaskMainStatus_5, 5, 1, 1, 1)
        self.TaskMainStatus_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMainStatus_6.setObjectName("TaskMainStatus_6")
        self.gridLayout_2.addWidget(self.TaskMainStatus_6, 6, 1, 1, 1)
        self.TaskMainStatus_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMainStatus_7.setObjectName("TaskMainStatus_7")
        self.gridLayout_2.addWidget(self.TaskMainStatus_7, 7, 1, 1, 1)
        self.TaskMainStatus_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMainStatus_8.setObjectName("TaskMainStatus_8")
        self.gridLayout_2.addWidget(self.TaskMainStatus_8, 8, 1, 1, 1)
        self.TaskMinorStatus_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMinorStatus_1.setObjectName("TaskMinorStatus_1")
        self.gridLayout_2.addWidget(self.TaskMinorStatus_1, 1, 2, 1, 1)
        self.TaskMinorStatus_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMinorStatus_2.setObjectName("TaskMinorStatus_2")
        self.gridLayout_2.addWidget(self.TaskMinorStatus_2, 2, 2, 1, 1)
        self.TaskMinorStatus_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMinorStatus_3.setObjectName("TaskMinorStatus_3")
        self.gridLayout_2.addWidget(self.TaskMinorStatus_3, 3, 2, 1, 1)
        self.TaskMinorStatus_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMinorStatus_4.setObjectName("TaskMinorStatus_4")
        self.gridLayout_2.addWidget(self.TaskMinorStatus_4, 4, 2, 1, 1)
        self.TaskMinorStatus_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMinorStatus_5.setObjectName("TaskMinorStatus_5")
        self.gridLayout_2.addWidget(self.TaskMinorStatus_5, 5, 2, 1, 1)
        self.TaskMinorStatus_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMinorStatus_6.setObjectName("TaskMinorStatus_6")
        self.gridLayout_2.addWidget(self.TaskMinorStatus_6, 6, 2, 1, 1)
        self.TaskMinorStatus_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMinorStatus_7.setObjectName("TaskMinorStatus_7")
        self.gridLayout_2.addWidget(self.TaskMinorStatus_7, 7, 2, 1, 1)
        self.TaskMinorStatus_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.TaskMinorStatus_8.setObjectName("TaskMinorStatus_8")
        self.gridLayout_2.addWidget(self.TaskMinorStatus_8, 8, 2, 1, 1)
        self.PbGetStatus_2 = QtWidgets.QPushButton(Form)
        self.PbGetStatus_2.setGeometry(QtCore.QRect(930, 840, 121, 23))
        self.PbGetStatus_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbGetStatus_2.setObjectName("PbGetStatus_2")
        self.PbGetStatus_3 = QtWidgets.QPushButton(Form)
        self.PbGetStatus_3.setGeometry(QtCore.QRect(930, 870, 121, 23))
        self.PbGetStatus_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.PbGetStatus_3.setObjectName("PbGetStatus_3")

        self.retranslateUi(Form)
        self.Pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.PbClearMaster.setText(_translate("Form", "Clear"))
        self.PbClearDebug.setText(_translate("Form", "Clear"))
        self.label_5.setText(_translate("Form", "DATA"))
        self.label_4.setText(_translate("Form", "COMMAND ID"))
        self.label_3.setText(_translate("Form", "ACTION"))
        self.PbSendTest.setText(_translate("Form", "SEND TEST MESSAGE"))
        self.PbAddCommand.setText(_translate("Form", "ADD COMMAND"))
        self.PbDeleteCommand.setText(_translate("Form", "REMOVE COMMAND"))
        self.PbSendDataToTask.setText(_translate("Form", "SEND DATA TO TASK"))
        self.CbMotorMode.setItemText(0, _translate("Form", "FREERUN BLOCKING"))
        self.CbMotorMode.setItemText(1, _translate("Form", "FREERUN NON BLOCKING"))
        self.CbMotorMode.setItemText(2, _translate("Form", "STEP BLOCKING"))
        self.CbMotorMode.setItemText(3, _translate("Form", "STEP NONBLOCKING"))
        self.CbMotorDirection.setItemText(0, _translate("Form", "FOWARD"))
        self.CbMotorDirection.setItemText(1, _translate("Form", "BACKWARD"))
        self.label_10.setText(_translate("Form", "Direction"))
        self.label_12.setText(_translate("Form", "Timeout"))
        self.label_9.setText(_translate("Form", "Motor Mode"))
        self.label_11.setText(_translate("Form", "Steps"))
        self.PbSendMotorCommand.setText(_translate("Form", "SEND MOTOR COMMAND"))
        self.PbGetStatus.setText(_translate("Form", "GET STATUS"))
        self.CbBaudMaster.setItemText(0, _translate("Form", "9600"))
        self.CbBaudMaster.setItemText(1, _translate("Form", "115200"))
        self.PbConnectMaster.setText(_translate("Form", "CONNECT"))
        self.PbDisconnectMaster.setText(_translate("Form", "DISCONNECT"))
        self.label.setText(_translate("Form", "MASTER"))
        self.PbRefreshPorts.setText(_translate("Form", "REFRESH PORTS"))
        self.label_2.setText(_translate("Form", "DEBUG"))
        self.CbPrintIncomingHex.setText(_translate("Form", "Print Incoming Hex"))
        self.TaskId_5.setText(_translate("Form", "Task ID"))
        self.TaskId_3.setText(_translate("Form", "Task ID"))
        self.label_8.setText(_translate("Form", "MINOR STATUS"))
        self.TaskId_4.setText(_translate("Form", "Task ID"))
        self.TaskId_7.setText(_translate("Form", "Task ID"))
        self.label_7.setText(_translate("Form", "MAIN STATUS"))
        self.TaskId_6.setText(_translate("Form", "Task ID"))
        self.label_6.setText(_translate("Form", "TASK ID"))
        self.TaskId_2.setText(_translate("Form", "Task ID"))
        self.TaskId_1.setText(_translate("Form", "Task ID"))
        self.TaskId_8.setText(_translate("Form", "Task ID"))
        self.TaskMainStatus_1.setText(_translate("Form", "Task MainS"))
        self.TaskMainStatus_2.setText(_translate("Form", "Task MainS"))
        self.TaskMainStatus_3.setText(_translate("Form", "Task MainS"))
        self.TaskMainStatus_4.setText(_translate("Form", "Task MainS"))
        self.TaskMainStatus_5.setText(_translate("Form", "Task MainS"))
        self.TaskMainStatus_6.setText(_translate("Form", "Task MainS"))
        self.TaskMainStatus_7.setText(_translate("Form", "Task MainS"))
        self.TaskMainStatus_8.setText(_translate("Form", "Task MainS"))
        self.TaskMinorStatus_1.setText(_translate("Form", "Task MinorS"))
        self.TaskMinorStatus_2.setText(_translate("Form", "Task MinorS"))
        self.TaskMinorStatus_3.setText(_translate("Form", "Task MinorS"))
        self.TaskMinorStatus_4.setText(_translate("Form", "Task MinorS"))
        self.TaskMinorStatus_5.setText(_translate("Form", "Task MinorS"))
        self.TaskMinorStatus_6.setText(_translate("Form", "Task MinorS"))
        self.TaskMinorStatus_7.setText(_translate("Form", "Task MinorS"))
        self.TaskMinorStatus_8.setText(_translate("Form", "Task MinorS"))
        self.PbGetStatus_2.setText(_translate("Form", "Start statusClock"))
        self.PbGetStatus_3.setText(_translate("Form", "Stop statusClock"))
